version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    working_directory: /home/circleci/project/Assignment3  # Adjust to your subdirectory name
    steps:
      - checkout
      - run:
          name: Compile Java Code
          command: mvn compile
      - store_artifacts:
          path: target/classes
          destination: class-files
workflows:
  build-workflow:
    jobs:
      - build
