version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    working_directory: /home/circleci/project/studies/cs_501/asgmt/501_hw_03
    steps:
      - checkout
      - run:
          name: List Root Directory Contents
          command: ls -la /home/circleci/project
      - run:
          name: List Project Directory Contents
          command: ls -la /home/circleci/project/studies/cs_501/asgmt/501_hw_03 || echo "Directory not found"
      - run:
          name: Compile Java Code
          command: mvn compile
      - store_artifacts:
          path: target/classes
          destination: class-files
workflows:
  build-workflow:
    jobs:
      - build
