jobs:
  build_501_hw_03:
    docker:
      - image: cimg/openjdk:11.0
    working_directory: /home/circleci/project/studies/cs_501/asgmt/501_hw_03
    steps:
      - checkout
      - run:
          name: Compile 501_hw_03
          command: mvn compile
      - store_artifacts:
          path: target/classes
          destination: 501_hw_03_class-files
workflows:
  build-workflow:
    jobs:
      - build_501_hw_03
